name: kuwa
services:
  web:
    image: kuwaai/multi-chat-web
    build:
      context: ../../
      dockerfile: docker/web/Dockerfile
    restart: unless-stopped
    environment:
      TRUST_DOWNSTREAM_PROXY: true
      DEFAULT_HOST: ${DOMAIN_NAME}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - multi-chat-storage:/app/storage:ro
    ports: ["80:80", "443:443"]
    depends_on: ["multi-chat"]
    networks: ["frontend"]
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://${DOMAIN_NAME}/"]
      timeout: 10s
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  multi-chat:
    image: kuwaai/multi-chat
    build:
      context: ../../
      dockerfile: docker/multi-chat/Dockerfile
    restart: unless-stopped
    init: true
    depends_on:
      - redis
    environment:
      # For nginx-proxy ("web" container) to generate configuration
      VIRTUAL_PROTO: fastcgi
      VIRTUAL_HOST_MULTIPORTS: |
        ${DOMAIN_NAME}:
          /index.php: {port: 9000}
          /app/: {port: 9001}
        web:
          /index.php: {port: 9000}
          /app/: {port: 9001}
      VIRTUAL_ROOT: /app/public
      VIRTUAL_PATH: /index.php
      
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: ${PUBLIC_BASE_URL}

      # Use sqlite as the default database
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/storage/database.sqlite

      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD_FILE: /run/secrets/admin-password
      NVIDIA_VISIBLE_DEVICES: all
    secrets:
      - admin-password
    volumes: [
      "multi-chat-storage:/app/storage:rw",
      "../root/custom:/app/resources/views/components/custom:ro",
      "../root:/var/kuwa/docker/root:rw",
    ]
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck"]
      timeout: 10s
    networks: ["frontend", "backend"]

  kernel:
    image: kuwaai/kernel
    build:
      context: ../../
      dockerfile: docker/kernel/Dockerfile
    restart: unless-stopped
    networks: ["backend"]

  redis:
    image: redis:6.0.20
    restart: always
    networks:
      - backend

  executor-builder:
    image: kuwaai/model-executor
    build:
      context: ../../
      dockerfile: docker/executor/Dockerfile
      platforms:
        - "linux/amd64"
        # - "linux/arm64"
    entrypoint: /bin/bash -c
    command: ["echo Image builds completed."]

volumes:
  multi-chat-storage: {}
  kuwa-root: # The root of Kuwa filesystem hierarchy to store user-uploaded data during runtime.
    driver: local
    driver_opts:
      type: none
      device: "../root"
      o: bind

secrets:
  admin-password:
    file: ../.admin-password

networks:
  frontend: {}
  backend: {}