services:
  chatgpt-executor:
    image: kuwaai/model-executor
    environment:
      EXECUTOR_TYPE: chatgpt
      EXECUTOR_ACCESS_CODE: .model/openai/chatgpt
      EXECUTOR_NAME: ChatGPT
      EXECUTOR_ORDER: 401100
      EXECUTOR_IMAGE: chatgpt.png # Refer to src/multi-chat/public/images
    depends_on:
      - executor-builder
      - kernel
    command: [
      #"--temperature", "0.2"
    ]
    restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"
    networks: ["backend"]