services:
  copycat-executor:
    image: kuwaai/model-executor
    environment:
      EXECUTOR_TYPE: debug
      EXECUTOR_ACCESS_CODE: tool/copycat
      EXECUTOR_NAME: CopyCat
      EXECUTOR_IMAGE: copy.png # Refer to src/multi-chat/public/images
    depends_on:
      - executor-builder
      - kernel
    command: ["--delay", "0.02", "--log", "debug"]
    restart: unless-stopped
    networks: ["backend"]