services:
  copycat-executor:
    extends:
      file: executor_base.yaml
      service: executor-base
    depends_on:
      - executor-builder
    environment:
      EXECUTOR_TYPE: debug
      EXECUTOR_ACCESS_CODE: .tool/kuwa/copycat
      EXECUTOR_NAME: CopyCat
      EXECUTOR_ORDER: 999000
      EXECUTOR_IMAGE: copy.png # Refer to src/multi-chat/public/images
    command: ["--delay", "0.02", "--log", "debug"]