services:
  web:
    environment:
      DEBUG_ENDPOINT: "true"
  multi-chat:
    environment:
      APP_ENV: development
      APP_DEBUG: true
      - ../multi-chat/add-executor.php:/app/app/Console/add-executor.php
      - ../multi-chat/check-update.php:/app/app/Console/check-update.php
      - ../multi-chat/update-project.php:/app/app/Console/update-project.php
  db-ui:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - backend