services:
  docqa-executor:
    image: kuwaai/model-executor
    environment:
      CUSTOM_EXECUTOR_PATH: ./docqa/docqa.py
      EXECUTOR_ACCESS_CODE: doc-qa;web-qa;db-qa
      EXECUTOR_NAME: Document QA;Web QA;DB QA
      EXECUTOR_IMAGE: doc-qa.png;web-qa.png;db-qa.png # Refer to src/multi-chat/public/images
      EXECUTOR_CREATE_BOT: true;true;true
      TRANSFORMERS_OFFLINE: ${TRANSFORMERS_OFFLINE:-0} # For embedding model
    depends_on:
      - executor-builder
      - kernel
      - multi-chat
    command: [
      "--api_base_url", "http://web/",
      "--model", "geminipro",
      "--log", "debug"
      ]
    volumes: [
      "kuwa-root:/var/kuwa/docker/root:rw", # The root of Kuwa filesystem hierarchy to store user-uploaded data during runtime.
      "~/.cache/huggingface:/root/.cache/huggingface"
    ]
    extra_hosts:
      - "localhost:host-gateway"
    restart: unless-stopped
    networks: ["backend", "frontend"]