services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - 38788:5678
    environment:
      - GENERIC_TIMEZONE=Asia/Taipei
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: