services:
  nim-executor:
    image: kuwaai/model-executor
    environment:
      EXECUTOR_TYPE: nim
      EXECUTOR_ACCESS_CODE: .model:nim/
      EXECUTOR_NAME: NIM API
      EXECUTOR_IMAGE: nim.png # Refer to src/multi-chat/public/images
      EXECUTOR_ORDER: 401200
      EXECUTOR_CREATE_BOT: false
    depends_on:
      - executor-builder
      - kernel
    command: [
      "--log", "debug",
      "--context_window", "131072",

      # By default will user the API key from user. 
      # If you want to use system-wise API key, enable following settings.
      # "--no_override_api_key", # Disable override the system API key with user API key.
      # "--api_key", "YOUR_API_KEY", # Input the API key that you have applied for
    ]
    restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"
    networks: ["backend"]