services:
  painter-executor:
    extends:
      file: executor_base.yaml
      service: executor-base
    depends_on:
      - executor-builder
    environment:
      CUSTOM_EXECUTOR_PATH: ./image_generation/main.py
      EXECUTOR_ACCESS_CODE: painter
      EXECUTOR_NAME: Painter
      EXECUTOR_IMAGE: painter.png # Refer to src/multi-chat/public/images
      HUGGING_FACE_HUB_TOKEN: ${HUGGING_FACE_HUB_TOKEN}
    command: []