services:
  uploader-executor:
    image: kuwaai/model-executor
    environment:
      CUSTOM_EXECUTOR_PATH: ./uploader/main.py
      EXECUTOR_ACCESS_CODE: .tool/kuwa/uploader
      EXECUTOR_NAME: Uploader
      EXECUTOR_ORDER: 999020
      EXECUTOR_CREATE_BOT: false
      EXECUTOR_IMAGE: upload.png # Refer to src/multi-chat/public/images
    depends_on:
      - executor-builder
      - kernel
      - multi-chat
    command: [
      "--api_base_url", "http://web/",
      "--log", "debug"
    ]
    volumes: [
      "kuwa-root:/var/kuwa/docker/root:rw", # The root of Kuwa filesystem hierarchy to store user-uploaded data during runtime.
    ]
    extra_hosts:
      - "localhost:host-gateway"
    restart: unless-stopped
    networks: ["backend", "frontend"]