[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/kuwa"]

[tool.hatch.version]
source = "vcs"
raw-options = {root = "../../../"}

[tool.hatch.build.hooks.vcs]
version-file = "src/kuwa/rag/_version.py"

[tool.hatch.metadata.hooks.vcs]

[project]
name = "kuwa-rag"
dynamic = ["version"]
authors = [
  { name="Yung-Hsiang Hu", email="iftnt1999@gmail.com" },
]
description = "The RAG library of Kuwa GenAI OS."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies=[
  'requests ~= 2.32.3',
  'selenium ~= 4.23.1',
  'bs4 ~= 0.0.2',
  'markitdown[pdf, docx, pptx, xlsx, xls] ~= 0.1.1',
  'pdfminer.six >= 20250327',
  'trafilatura ~= 1.9.0',
  'magika ~= 0.6.1',
  'langchain ~= 0.2.12',
  'langchain-community ~= 0.2.11',
  'langchain-huggingface ~= 0.0.3',
  'sentence-transformers ~= 3.0.1',
  'faiss-cpu ~= 1.8.0.post1', # Since the count of documents is relatively small, CPU is enough.
  'rank_bm25',
]

[project.urls]
"Homepage" = "https://kuwaai.tw/os/Intro"
"Bug Tracker" = "https://github.com/kuwaai/genai-os/issues"